perf(init): optimize boot time
This commit changes init scripts to POSIX-compliant syntax and uses
`ash` in their hashbang for optimized speed.

I also rewrote/optimized most of them as I stumbled upon code that could
be optimized or made more readable.

In order to fix how the wifi is initialized (with 2 hard `sleep`), I had
to reorganize the init scripts order, specifically:
* `populate` was `04`, it's now `01`
* `acpid` was `05` (b/c it required `S04populate`), it's now `02` (its default)

diff --git a/board/recalbox/fsoverlay/etc/init.d/S03splash b/board/recalbox/fsoverlay/etc/init.d/S03splash
--- a/board/recalbox/fsoverlay/etc/init.d/S03splash
+++ b/board/recalbox/fsoverlay/etc/init.d/S03splash
@@ -1,140 +1,118 @@
-#!/bin/bash
+#!/bin/ash
 
-selectVideo() {
-IFS='
-'
-fbdev_height=$(cat /sys/class/graphics/fb0/virtual_size | cut -d, -f2)
-videoSubFolder=""
-if [[ $videolength -lt 241 ]]; then
+if [ "$1" != "start" ]; then
+  exit 0
+fi
+
+# on some sytems, fb0 is not immediatly loaded,
+# so, give it a chance by waiting a bit (5 seconds, then fail hard)
+count=0
+until [ -e /dev/fb0 ]; do
+  if [ ${count} -ge 50 ]; then
+    exit 1
+  else
+    sleep 0.1
+    let count++
+  fi
+done
+
+## Functions ##
+
+# selectVideo
+#  takes no argument and outputs a random video from those available
+#  (uses 240p videos if framebuffer height is 240px or less)
+function selectVideo() {
+  if [ ${fbdevHeight} -le 240 ]; then
     videoSubFolder="/240p"
+  fi
+  IFS= find /recalbox/system/resources/splash${videoSubFolder} -name *.mp4 \
+    | while read line; do echo "$RANDOM ${line}"; done \
+    | sort -n \
+    | head -1 \
+    | cut -d' ' -f2
+}
+
+# stopPlayerWhenFrontendReady <playerPID> <timeout>
+#   stops player running with PID <playerPID> when either (whichever comes first):
+#     - EmulationStation is ready
+#     - Kodi is ready
+#     - after <timeout> seconds
+function stopPlayerWhenFrontendReady() {
+  local playerPID="$1"
+  local timeout="$2"
+  local count=0
+
+  [ ${timeout} -eq -1 ] && return
+  until [ -f "/tmp/emulationstation.ready" ] || [ -e "/var/run/kodi.msg" ] || [ ${count} -ge ${timeout} ]; do
+    sleep 1
+    let count++
+  done
+  kill -9 ${playerPID}
+}
+
+# playWithFFPlay
+#   starts playing a video on the framebuffer via ffplay
+function playWithFFPlay() {
+  local videoFile="$(selectVideo)"
+
+  if ! which ffplay > /dev/null; then
+    return
+  fi
+  ffplay_opts="-hide_banner -autoexit"
+  ffplay_srt="subtitles=/recalbox/system/resources/splash/recalboxintro.srt:force_style='FontName=/usr/share/fonts/dejavu/DejaVuSans-BoldOblique.ttf,Fontsize=10'"
+  ffplay ${ffplay_opts} -x ${fbdevWidth} -y ${fbdevHeight} -vf "${ffplay_srt}" "${videoFile}" > /dev/null 2>&1 &
+  if [ ${videoLength} -ne -1 ]; then
+    stopPlayerWhenFrontendReady $! ${videoLength}
+  fi
+}
+
+# playWithOMX
+#   starts playing an intro video via OMX player
+function playWithOMX() {
+  local videoFile="$(selectVideo)"
+
+  if ! which omxplayer.bin > /dev/null; then
+    return
+  fi
+  omx_fnt="--font=/usr/share/fonts/dejavu/DejaVuSans-BoldOblique.ttf"
+  omx_opt="--adev both --no-keys --layer=10000 --aspect-mode=fill"
+  omx_srt="--no-ghost-box --lines=1 --align=left $omx_fnt --font-size=20 --subtitles=/recalbox/system/resources/splash/recalboxintro.srt"
+  /usr/bin/omxplayer.bin ${omx_opt} ${omx_srt} ${videoFile} &
+  if [ ${videoLength} -ne -1 ]; then
+    stopPlayerWhenFrontendReady $! ${videoLength}
+  fi
+}
+
+# showIntroBackground
+#   displays our intro background via the framebuffer
+showIntroBackground() {
+  fbv -f -i /recalbox/system/resources/splash/logo-version.png
+}
+
+# showInstallBackground
+#   displays our install background via the framebuffer
+showInstallBackground() {
+  fbv -f -i /tmp/.install.png
+}
+
+## Global variables ##
+
+videoLength=$(sed -n "s/^system.splash.length=//p" /boot/recalbox-backup.conf)
+if [ -z "${videoLength}" ] || [ ${videoLength} -eq 0 ] || [ ${videoLength} -lt -1 ]; then
+  videoLength=20
 fi
-videoList=($(find /recalbox/system/resources/splash${videoSubFolder} -name *.mp4))
-videoNumber=${#videoList[*]}
-video=${videoList[$((RANDOM%videoNumber))]}
-echo "${video}"
-}
-video="`selectVideo`"
 
-videolength=`egrep "^system.splash.length" /boot/recalbox-backup.conf|sed "s/system.splash.length=//g"`
-if [[ -z $videolength || $videolength -eq 0 || $videolength -lt -1 ]] ; then
-	videolength=20
+fbdevWidth=$(cut -d, -f1 /sys/class/graphics/fb0/virtual_size)
+fbdevHeight=$(cut -d, -f2 cat /sys/class/graphics/fb0/virtual_size)
+
+## Main ##
+
+if [ -f /tmp/.install.png ]; then
+  showInstallBackground &
+elif [ "$(head -c 3 /recalbox/recalbox.arch)" = "rpi" ]; then
+  ( playWithOMX ; showIntroBackground ) &
+else
+  ( playWithFFPlay; showIntroBackground ) &
 fi
 
-do_ffmpeg_start () {
-    if ! `which ffplay >/dev/null` || [[ ! -f $video ]] ; then
-        return
-    fi
-    ffplay_opts="-hide_banner -autoexit"
-    ffplay_srt="subtitles=/recalbox/system/resources/splash/recalboxintro.srt:force_style='FontName=/usr/share/fonts/dejavu/DejaVuSans-BoldOblique.ttf,Fontsize=10'"
-    fbdev_width=$(cat /sys/class/graphics/fb0/virtual_size | cut -d, -f1)
-    fbdev_height=$(cat /sys/class/graphics/fb0/virtual_size | cut -d, -f2)
-    ffplay ${ffplay_opts} -x ${fbdev_width} -y ${fbdev_height} -vf "${ffplay_srt}" "${video}" >/dev/null 2>&1 &
-    PID=$!
-    count=0
-    if [[ $videolength -gt -1 ]]; then
-        while [[ ! -f "/tmp/emulationstation.ready" && ! -e "/var/run/kodi.msg" && $count -lt $(($videolength*10)) ]]; do
-            sleep 0.1
-            ((count++))
-        done
-    fi
-    do_ffmpeg_stop $PID
-    show_logo
-}
-
-do_ffmpeg_stop () {
-    kill -9 $1
-}
-
-do_omx_start ()
-{
-    # odroid xu4 has not omxplayer, make it run this code make it flash
-    if [[ ! -f $video || ! -f /usr/bin/omxplayer ]]; then
-        return
-    fi
-
-    # Initialize dbus session
-    OMXPLAYER_DBUS_ADDR="/tmp/omxplayerdbus.root"
-    OMXPLAYER_DBUS_PID="/tmp/omxplayerdbus.root.pid"
-    exec 5> "$OMXPLAYER_DBUS_ADDR"
-    exec 6> "$OMXPLAYER_DBUS_PID"
-    dbus-daemon --fork --print-address 5 --print-pid 6 --session
-    until [ -s "$OMXPLAYER_DBUS_ADDR" ]; do
-        echo "waiting for dbus address to appear" >&2
-        sleep .2
-    done
-    DBUS_SESSION_BUS_ADDRESS=`cat $OMXPLAYER_DBUS_ADDR`
-    DBUS_SESSION_BUS_PID=`cat $OMXPLAYER_DBUS_PID`
-    export DBUS_SESSION_BUS_ADDRESS
-    export DBUS_SESSION_BUS_PID
-
-    # Launch the video
-    omx_fnt="--font=/usr/share/fonts/dejavu/DejaVuSans-BoldOblique.ttf"
-    omx_opt="--adev both --no-keys --layer=10000 --aspect-mode=fill"
-    omx_srt="--no-ghost-box --lines=1 --align=left $omx_fnt --font-size=20 --subtitles=/recalbox/system/resources/splash/recalboxintro.srt"
-    /usr/bin/omxplayer.bin $omx_opt $omx_srt $video &
-    PID=$!
-
-    # Stop the video when ready
-    if [[ $? -eq 0 && $videolength -gt -1 ]]; then
-        recallog "Let's play the video for $videolength seconds"
-        # Wait for emulationstation or Kodi, but not more than $videolength seconds
-        count=0
-        while [[ ! -f "/tmp/emulationstation.ready" && ! -e "/var/run/kodi.msg" && $count -lt $videolength ]]; do
-            sleep 1
-            ((count++))
-        done
-        # Finish with a one second fade out.
-        audio_fade=1
-        video_fade=250
-        while [[ $video_fade -gt 0 ]]; do
-            sleep .02
-            dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Volume double:$audio_fade >/dev/null
-            dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.SetAlpha objpath:/not/used int64:$video_fade >/dev/null
-            audio_fade=`echo "$audio_fade .02" | awk '{printf "%.2f", $1-$2}'`
-            ((video_fade=video_fade-5))
-        done
-        # Ready flag set or timeout occured; stop video process.
-        dbus-send --print-reply=literal --session --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Action int32:15 >/dev/null
-    else
-        recallog "Let's play the video entirely"
-    fi
-}
-
-wait_for_fb () {
-    # on some sytems, fb0 is not immediatly loaded, so, keep a chance by waiting a bit
-    N=0
-    while ! test -e /dev/fb0 -o $N -gt 15
-    do
-        sleep 1
-        let N++
-    done
-}
-
-show_logo() {
-    wait_for_fb
-    test -e /dev/fb0 && fbv -f -i /recalbox/system/resources/splash/logo-version.png
-}
-
-show_install_logo() {
-    wait_for_fb
-    test -e /dev/fb0 && fbv -f -i /tmp/.install.png
-}
-
-case "$1" in
-    start)
-        if [[ -f /tmp/.install.png ]] ; then
-            ( wait_for_fb ; show_install_logo ) &
-        elif [[ `cat /recalbox/recalbox.arch` == "rpi"* ]] ; then
-            ( do_omx_start ; show_logo ) &
-        else
-            ( wait_for_fb ; do_ffmpeg_start ) &
-        fi
-        ;;
-    stop)
-        ;;
-    restart|reload)
-        ;;
-    *)
-esac
-
-exit $?
+exit 0
diff --git a/board/recalbox/fsoverlay/etc/init.d/S09wifi b/board/recalbox/fsoverlay/etc/init.d/S09wifi
--- a/board/recalbox/fsoverlay/etc/init.d/S09wifi
+++ b/board/recalbox/fsoverlay/etc/init.d/S09wifi
@@ -1,92 +1,92 @@
-#!/bin/bash
+#!/bin/ash
 
-# Function to create connmann wifi profiles based on user settings
+if [ "$1" != "start" ]; then
+  exit 0
+fi
 
-rb_wifi_boot_configure() {
-        [ "$1" = "1" ] && X="" || X="$1"
-        settings_ssid=`egrep -m1 "^wifi${X}.ssid" /boot/recalbox-backup.conf|sed "s/wifi${X}.ssid=//g"`
-        settings_key=`egrep -m1 "^wifi${X}.key" /boot/recalbox-backup.conf|sed "s/wifi${X}.key=//g"`
-        settings_file="/var/lib/connman/recalbox_wifi${X}.config"
-        [ "$1" = "1" ] && settings_name="default" || settings_name="${X}"
+## Functions ##
 
+# readSetting <setting>
+#   returns the setting value in /boot/recalbox-backup.conf
+function readSetting() {
+  local setting="$1"
+  echo "${recalboxConfig}" | sed -n "s/^${setting}=\(.*\)$/\1/p" | head -1
+}
 
-        settings_ip=`egrep -m1 "^wifi${X}.ip" /boot/recalbox-backup.conf|sed "s/wifi${X}.ip=//g"`
-        settings_gateway=`egrep -m1 "^wifi${X}.gateway" /boot/recalbox-backup.conf|sed "s/wifi${X}.gateway=//g"`
-        settings_netmask=`egrep -m1 "^wifi${X}.netmask" /boot/recalbox-backup.conf|sed "s/wifi${X}.netmask=//g"`
+# waitForConnmanDaemon
+#   sleeps until connmand is started, up to 2 seconds
+function waitForConnmanDaemon() {
+  local count=0
 
-	settings_manual_section=""
-        if [[ "$settings_ip" != "" ]] && \
-	   [[ "$settings_gateway" != "" ]] && \
-	   [[ "$settings_netmask" != "" ]] ;then
-	   settings_manual_section="
-IPv4=${settings_ip}/${settings_netmask}/${settings_gateway}"
-	fi
-        if [[ "$settings_ssid" != "" ]] ;then
+  until connmanctl state; do
+    if [ ${count} -gt 20 ]; then
+      recallog -f init.log "Error: Connmand not ready. Cannot configure it."
+      exit 1
+    else
+      sleep 0.1
+      let count++
+    fi
+  done
+}
 
-	recallog "Recovering wifi for SSID: $settings_ssid"
+# writeConnmanConfig [number]
+#   creates a configuration file for Connman, with values from /boot/recalbox-backup.conf
+#   [number] can be 2 or 3 (default is empty), it allows us to have 3 configured networks
+function writeConnmanConfig() {
+  local configIndex="$1"
+  local outputFile="/var/lib/connman/recalbox_wifi${configIndex}.config"
+  local ssid=$(readSetting "wifi${configIndex}.ssid")
+  local key=$(readSetting "wifi${configIndex}.key")
+  local ip=$(readSetting "wifi${configIndex}.ip")
+  local netmask=$(readSetting "wifi${configIndex}.netmask")
+  local gateway=$(readSetting "wifi${configIndex}.gateway")
 
-        mkdir -p "/var/lib/connman"
-        cat > "${settings_file}" <<EOF
+  if [ -n "${ssid}" ]; then
+    recallog "Recovering wifi configuration for SSID: ${ssid}"
+    mkdir -p "/var/lib/connman"
+    cat > "${outputFile}" <<EOF
 [global]
 Name=recalbox
 
-[service_recalbox_${settings_name}]
+[service_recalbox_${configIndex:-default}]
 Type=wifi
-Name=${settings_ssid}${settings_manual_section}
+Name=${ssid}
 EOF
-        if test "${settings_key}" != ""
-        then
-            echo "Passphrase=${settings_key}" >> "${settings_file}"
-	fi
+    if [ -n "${ip}" ] && [ -n "${netmask}" ] && [ -n "${gateway}" ]; then
+      echo "IPv4=${ip}/${netmask}/${gateway}" >> "${outputFile}"
     fi
+    if [ -n "${key}" ]; then
+      echo "Passphrase=${key}" >> "${outputFile}"
+    fi
+  fi
 }
 
-# Main
+## Global variables ##
 
-case "$1" in
-  start)
-	if [ -f /boot/recalbox-backup.conf ]
-	then
-		if [ `egrep "^wifi.enabled" /boot/recalbox-backup.conf|sed "s/wifi.enabled=//g"` -ne 0  ]
-		then
-			recallog "Wifi option enabled, trying to configure"
-			sleep 2 # wait a bit to be sure tmpfs is initialized
-			for i in {1..3}; do
-				rb_wifi_boot_configure $i&
-			done
-			sleep 2 # wait a bit, otherwise, connman is not really started
-			/usr/bin/connmanctl enable wifi || exit 1
-			settings_region=`egrep "^wifi.region" /boot/recalbox-backup.conf|sed "s/wifi.region=//g"`
-			if [[ "$settings_region" != "" ]] ;then
-				recallog "Wifi region: ${settings_region}"
-				/usr/sbin/iw reg set "${settings_region}"
-			fi
-			/usr/bin/connmanctl scan   wifi || exit 1
-		else
-			recallog "Wifi option disabled"
-		fi
-	else
-		recallog "/boot/recalbox-backup.conf not found"
-	fi
+recalboxConfig=$(cat /boot/recalbox-backup.conf 2> /dev/null)
 
-	# If share over network, let's add a timeout of 10 seconds (max) for slow networks
-	if [ `grep -c "^sharedevice=NETWORK$" /boot/recalbox-boot.conf` -ne 0 ]
-	then
-		try=0
-		until [ ! $try -lt 10 ]
-		do
-			if [ `ifconfig |grep -v "127.0.0.1"|grep -c "inet addr"` -gt 0 ]
-			then
-				break # Of course if network is OK, don't wait anymore!
-			fi
-			sleep 1
-			try=`expr $try + 1`
-		done
-	fi
-	;;
-  stop)
-	;;
-  *)
-esac
+## Main ##
 
-exit $?
+if [ -z "${recalboxConfig}" ]; then
+  recallog "No /boot/recalbox-backup.conf found to recover wifi configuration from."
+  exit 0
+fi
+
+if [ $(readSetting wifi.enabled) -ne 1  ]; then
+  recallog "Wifi option disabled"
+  exit 0
+fi
+
+recallog "Wifi option enabled, trying to configure"
+for i in '' 2 3; do
+  writeConnmanConfig $i
+done
+waitForConnmanDaemon
+connmanctl enable wifi || exit 1
+wifiRegion=$(readSetting wifi.region)
+if [ -n "${wifiRegion}" ]; then
+  recallog "Wifi region: ${wifiRegion}"
+  iw reg set "${wifiRegion}"
+fi
+
+exit 0
